<div class='about'>
    <h1 class='about__title'>About</h1>

    <h2 class='about__heading'>Where am I?</h2>
    <p class='about__paragraph'>You are currently in the “about section” of a website dedicated solely to sharing text (not just poetry, it could be literally anything, even a recipe, as long as its only plain text). It’s a very simple concept to say the least, however right now the website serves only as a blank canvas on which I plan to build something more robust and useful. It’s still undergoing the earliest stages of development, meaning that there will probably be lots of bugs and missing features, but don’t get discouraged! It will be improving over time as I add new things according to suggestions from the users.</p>
    <h2 class='about__heading'>How can I help?</h2>
    <p class='about__paragraph'>
        If you found a bug or want to see some sort of improvement in the next version, enter it in the following form:
    </p>
    <form class="submission-form" id="submission-form">
        <p class="submission-form__message"></p>
        <input type="text" name="subject" placeholder="Subject" class="submission-form__subject"></input>
        <textarea name="description" placeholder="Description" class="submission-form__description" style="overflow:hidden" rows='10' autocomplete="off" cols='50'></textarea>
        <input type="submit" name="submit" class="submission-form__submit" >
    </form>
    <p class='about__paragraph'>
        If you want to contribute directly, contact me at <a href="mailto:jakub.mann@slumpoetry.cz?Subject=Contribution" target="_top">jakub.mann@slumpoetry.cz</a>
    </p>
    <h2 class='about__heading'>Are you even working on it?</h2>
    <p class='about__paragraph'>To see latest changes, visit <a href="/log.html">the update log</a>.</p>
</div>
