<div class='about'>
    <h1 class='about__title'>About</h1>

    <h2 class='about__heading'>What is this website?</h2>
    <p class=' about__paragraph about__paragraph--strong'>
        Ever thought about writing a poem?
    </p>
    <p class='about__paragraph'>
        If you answered yes, than this is the place for you. If you answered no, even better! If you never thought about it, now is the time to start.
    </p>
    <p class='about__paragraph'>
        What you write depends only on your imagination. You could write a poem, but you don’t have to, because if you don’t feel like writing, there is still a lot to read and get inspired by.
        If you choose to write, your poem will be shown anonymously to a nonjudgmental community (even if they were judgmental, I didn’t yet give them a way of expressing it).
    </p>
    <h2 class='about__heading'>How can I help?</h2>
    <p class='about__paragraph'>
        Choosing to help and not expect a reward is truly a virtue. If you come up with an idea to improve the website, or find a bug, you can enter it in the following form:
    </p>
    <form class="submission-form" id="submission-form">
        <p class="submission-form__message"></p>
        <input type="text" name="subject" placeholder="Subject" class="submission-form__subject"></input>
        <textarea name="description" placeholder="Description" class="submission-form__description" style="overflow:hidden" rows='10' autocomplete="off" cols='50'></textarea>
        <input type="submit" name="submit" class="submission-form__submit" >
    </form>
    <p class='about__paragraph'>
        If you want to contribute directly, contact me at <a href="mailto:jakub.mann@slumpoetry.cz?Subject=Contribution" target="_top">jakub.mann@slumpoetry.cz</a>
    </p>
    <h2 class='about__heading'>Are you even working on it?</h2>
    <p class='about__paragraph'>To see latest changes, visit <a href="/log.html">the update log</a>.</p>
</div>
