<div class='home'>
    <h1 class='home__title'>Home</h1>
    <?php
    session_start();

    if (isset($_SESSION['user_id'])) {
        require 'submit.phtml';
    }
    ?>
    <div class='posts'>
    <?php
      ob_start();
      foreach ($posts as $post) {
          ob_start();
          $postdata = $post->getcontent();
          require 'post.phtml';
          ob_end_flush();
      }
      ob_end_flush();
    ?>
    </div>
</div>
