<!doctype html>
<html>
    <head>
        <title><?= $title . " | Slum"; ?></title>
        <style>
        <?=file_get_contents('css/main.css')?>
        </style>
        <meta charset="UTF-8">
        <meta name="description" content="A website for sharing text">
        <meta name="keywords" content="Text, Poetry">
        <meta name="author" content="Jakub Mann">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono|IBM+Plex+Sans|IBM+Plex+Sans+Condensed|IBM+Plex+Serif" rel="stylesheet">
        <link rel="icon" type="image/png" href="/img/favicon.png">
        <link rel="apple-touch-icon" type="image/png" href="/img/favicon.png">
        <script type='text/javascript' src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script type='text/javascript' src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.js"></script>
        <script type='text/javascript'>
        <?=file_get_contents('js/main.js')?>
        </script>
    </head>

    <body>
        <?php require $filename ?>
    </body>
</html>
