<!doctype html>
<html>
    <head>
        <title><?= $title; ?></title>
        <link rel='stylesheet' type='text/css' href='/public/css/main.css'>  
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono|IBM+Plex+Sans|IBM+Plex+Sans+Condensed|IBM+Plex+Serif" rel="stylesheet">
        <meta charset="UTF-8">
    </head>

    <body>
        <?php require 'template/header.php'; ?>
        <div class='content'>
            <?php require $filename ?>
        </div> 
        <?php require 'template/footer.php'; ?>
    </body>
</html>
