<form class="login" id="login-form" method="POST">
		<input class="login__input" type="text" name="username" id="username" placeholder="Username/Email">

		<input class="login__input" type="password" name="password" id="password" placeholder="Password">

		<input type="hidden" name="token" value="<?=$_GET['token']?>">

		<button class="login__button_login" type="submit" name="submit">log in</button>

		<a class="login__button_register" href="/register">not registered?</a>
		<div class='login__error'>
        </div>
</form>
