<div class="register">
    <div class="register__title">
     <h1>Sign Up</h1>
    </div>
	<form class="register-form" method="POST" id='register-form'>
        <div id='error'>
        </div>

        <input class="register-form__input" type="text" id='username' name="username" placeholder="Username">

    	<input class="register-form__input" type="text" id='firstname' name="firstname" placeholder="First Name">


    	<input class="register-form__input" type="text" id='lastname' name="lastname" placeholder="Last Name">

    	<input class="register-form__input" type="text" id='email' name="email" placeholder="Email">

    	<input class="register-form__input" type="password" id='password' name="password" placeholder="Password">

    	<input class="register-form__input" type="password" id='password_confirm' name="password_confirm" placeholder="Confirm Password">

    	<button class="register-form__button" type="submit" name="submit">sign up</button>
        <p class="register__text">Only your username will be visible to other users</p>
	</form>
</div>
