<div class='submit_text'>
    <div id='error'>

    </div>
    <div class='submit_text__wrapper'>
        <form class='text-form' method='POST' id='text-form'>
            <input type='text'  placeholder='Title' autocomplete="off" name='title' class='text__title' id='title'>
            <textarea onkeyup="textAreaAdjust(this)" style="overflow:hidden" rows='10' autocomplete="off" cols='50' name ='body' class='text__body' id='body'></textarea>
            <button class="submit_button" type="submit" name="submit">Submit</button>
        </form>
    </div>
</div>
