<div class="user">
    <p class="user__username"><?=$user['username']?></h2>
    <br>
    <div class="userinfo">
        <p class="userinfo__name"><?='Name: ' . $user['firstname'] . ' ' . $user['lastname']?></p>
        <br>
        <p class="userinfo__email"><?='Email: ' . $user['email']?></p>
        <br>
        <p class="userinfo__regdate"><?='Joined: ' . $user['reg_date']?></p>
    </div>

    <?php
      ob_start();
      foreach ($posts as $post) {
          ob_start();
          $postdata = $post->getContent();
          require 'post.phtml';
          ob_end_flush();
      }
      ob_end_flush();
    ?>
</div>
